version: "3.8"

services:
  app:
    image: almuko/jonathan:latest
    ports:
      - "9090:9090"
    env_file: .env
    depends_on:
      - db

  db:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Zxcvbnm123
      POSTGRES_DB: jonathan
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
